# For development purposes. Since it builds the images, it needs to be executed from the root of the cloned repo
services:
  kv: 
    build: /kv
    image: riviga77/eoi-fastapi-kv
    container_name: kv
    ports:
      - "8000:8000"
    volumes:
      - ./kv:/code
  
  redis:
    image: "redis:latest"
    container_name: redis    
    volumes:
      - ./kv/data:/data

  predict: 
    build: /predict
    image: riviga77/eoi-fastapi-predict
    container_name: predict
    ports:
      - "8001:8000"
    volumes:
      - ./predict:/code

  tmdb: 
    build: /tmdb
    image: riviga77/eoi-fastapi-tmdb
    container_name: tmdb
    ports:
      - "8002:8000"
    volumes:
      - ./tmdb:/code
    environment:
      - API_KEY=$API_KEY_VALUE

  micro: 
    build: /micro
    image: riviga77/eoi-fastapi-micro
    container_name: micro
    ports:
      - "8003:8000"
    volumes:
      - ./micro:/code      

  ab:
    image: httpd
    container_name: apache-httpd

