# For production. It pulls the images from Docker Hub
services:
  kv:     
    image: riviga77/eoi-fastapi-kv
    container_name: kv
    ports: 
      - "8000:8000"
  
  redis:
    image: "redis:latest"
    container_name: redis    
    volumes:
      - ./redis_data:/data

  predict:     
    image: riviga77/eoi-fastapi-predict
    container_name: predict
    ports:
      - "8001:8000"    

  tmdb:     
    image: riviga77/eoi-fastapi-tmdb
    container_name: tmdb
    ports:
      - "8002:8000"    
    environment:
      - API_KEY=$API_KEY_VALUE

  micro:     
    image: riviga77/eoi-fastapi-micro
    container_name: micro
    ports:
      - "8003:8000"
      