# For development: Builds all images with volumes for code auto-reload
services:
  holamundo:     
    build: /holamundo
    image: riviga77/eoi-fastapi-holamundo
    container_name: holamundo
    ports:
      - "8000:8000"
    volumes:
      - ./holamundo:/code

  rest: 
    build: /rest
    image: riviga77/eoi-fastapi-rest
    container_name: rest
    ports:
      - "8001:8000"
    volumes:
      - ./rest:/code      

  kv: 
    build: /kv
    image: riviga77/eoi-fastapi-kv
    container_name: kv
    ports:
      - "8002:8000"
    volumes:
      - ./kv:/code
  
  redis:
    image: "redis:latest"
    container_name: redis    
    volumes:
      - ./kv/data:/data

  predict: 
    build: /predict
    image: riviga77/eoi-fastapi-predict
    container_name: predict
    ports:
      - "8003:8000"
    volumes:
      - ./predict:/code

  tmdb: 
    build: /tmdb
    image: riviga77/eoi-fastapi-tmdb
    container_name: tmdb
    ports:
      - "8004:8000"
    volumes:
      - ./tmdb:/code
    environment:
      - API_KEY=$API_KEY_VALUE

  micro: 
    build: /micro
    image: riviga77/eoi-fastapi-micro
    container_name: micro
    ports:
      - "8006:8000"
    volumes:
      - ./micro:/code      

  ab:
    image: httpd
    container_name: apache-httpd

