services:
  kv: 
    build: .
    image: eoi-fastapi-kv
    container_name: kv
    ports:
      - "8000:8000"
    volumes:
      - .:/code
  
  redis:
    image: "redis:latest"
    container_name: redis    
    volumes:
      - ./data:/data

