services:
  fastapi: 
    build: .
    image: riviga77/eoi-fastapi-tmdb
    container_name: eoi-fastapi-tmdb
    ports:
      - "8000:8000"
    volumes:
      - .:/code
    environment:
      - API_KEY=$API_KEY_VALUE